---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: happy-dev
  namespace: dev
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~0.1
spec:
  releaseName: happy-dev
  chart:
    git: git@github.com:drweber/happyBDay
    path: charts/happy
    ref: dev
  values:
    namespace: dev
    ingress:
      enabled: true
    containerPort: 8080
    image: drweber/happybday:0.1.0
    replicaCount: 1
