apiVersion: v1
kind: Service
metadata:
  name: happy-backend
  labels:
    app: happy
spec:
  selector:
    app: happy
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http